version: '2'
services:
  nginx:
    image: nginx:1.14.0
    ports:
     - "8088:80"
    volumes:
     - ./mkd2/:/mkd2/
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
        - php7.0
        - db
        - memcached
    container_name: mkd-nginx
  php7.0:
    build: ./php
    volumes:
     - ./mkd2/:/mkd2/
     - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
     - ./php/mail.ini:/usr/local/etc/php/conf.d/mail.ini
     - ./php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    links:
        - db
        - memcached
    container_name: mkd-php
    working_dir : /mkd2/
    cpuset: 0-3
  db:
    image: mysql:5.7
    ports:
     - "3308:3306"
    volumes: 
      - ./data:/var/lib/mysql
    environment:
        MYSQL_DATABASE: 'mkd2'
        MYSQL_ROOT_PASSWORD: 'admin123'
    container_name: mkd-db
  memcached:
    image: memcached
